spring:
  mvc:
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    include: oauth, db, credential, jwt

logging:
  file:
    name: logs/test.log  # 로깅 파일 위치
  level:
    org.hibernate.SQL: debug
    com.cookiee.cookieeserver: debug
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB

swagger:
  enabled: true
  base-package: com.cookiee.cookieeserver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**