name: Build and Deploy SpringBoot to EC2

on:
  push:
    branches: [ "master" ]
    
env:
  PROJECT_NAME: cookiee-
  BUCKET_NAME: cookiee-cicde-bucket
  CODE_DEPLOY_APP_NAME: cookiee-cicd
  DEPLOYMENT_GROUP_NAME: cookiee_instance

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"
          
      - name : Set up OAUTH file
        run : echo "${{ secrets.DEV_OAUTH }}" > ./src/main/resources/application-oauth.yml
        shell : bash
      - name : Set up CREDENTIAL file
        run : echo "${{ secrets.DEV_CREDENTIAL }}" > ./src/main/resources/application-credential.yml
        shell : bash
      - name : Set up DB file
        run : echo "${{ secrets.DEV_DB }}" > ./src/main/resources/application-db.yml
        shell : bash
      - name : Set up JWT file
        run : echo "${{ secrets.DEV_JWT }}" > ./src/main/resources/application-jwt.yml
        shell : bash
      - name : Set up APPLE file
        run : echo "${{ secrets.DEV_APPLE }}" > ./src/main/resources/static/Apple_AuthKey.p8
        shell : bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Gradle Build
        run: ./gradlew build

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment 
                --application-name $CODE_DEPLOY_APP_NAME 
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME 
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
